stages:
  - build
  - release      
  

build-job:
  stage: build
  script:
    - ls
    - echo "Compiling the code..."
    - echo "Compile complete."
    - echo "hello world" > hw.txt
  artifacts:
    paths:
      - "hw.txt"


create-release-job:
  stage: release
  script:
    - echo "Creating release"
    - Invoke-WebRequest -Uri http://automation.needful-apps.de/git-pull -Method POST


