stages:
  - build
  - release
  - notify_failure

build-job:
  stage: build
  script:
    - echo "Checking out the repository"
    - ls
    - echo "Compiling the code..."
    - echo "Compile complete."
    - echo "hello world" > hw.txt
  artifacts:
    paths:
      - hw.txt

release-job:
  only:
    - main
  stage: release
  needs: 
    - build-job
  script:
    - echo "Downloading artifact"
    - cp hw.txt /tmp/hw.txt
    - apk --no-cache add curl
    - echo "Triggering release"
    - curl -X POST http://automation.needful-apps.de/github-pull
    - echo "Sending release link to NextCloud Talk"
    - |
      curl -u "${NEXTCLOUD_USERNAME}:${NEXTCLOUD_PASSWORD}" \
        ${SERVER_ADDRESS}/send \
        -F "chatroom=${RELEASE_ROOM_ID}" \
        -F $'message=# Neue Version f\u00fcr ${CI_PROJECT_PATH}\nCommit-Meldung: ${CI_COMMIT_MESSAGE}'

failure-notification-job:
  only:
    - main
  stage: notify_failure
  needs: 
    - build-job
  when: on_failure
  script:
    - echo "Notifying failure via NextCloud Talk"
    - apk --no-cache add curl
    - |
      curl -u "${NEXTCLOUD_USERNAME}:${NEXTCLOUD_PASSWORD}" \
        ${SERVER_ADDRESS}/send \
        -F "chatroom=${FAIL_ROOM_ID}" \
        -F $'message=Job f\u00fcr ${CI_PROJECT_PATH} fehlgeschlagen.\nCommit-Meldung: ${CI_COMMIT_MESSAGE}\nLink: ${CI_JOB_URL}'