name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files
        run: ls

      - name: Compile Code
        run: |
          echo "Compiling the code..."
          echo "Compile complete."
          echo "hello world" > hw.txt

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hw-artifact
          path: hw.txt

  release:
    name: Release Job
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: hw-artifact

      - name: Create Release
        run: |
          curl -X POST http://automation.needful-apps.de/github-pull

      - name: Send link via NextCloud Talk
        env:
            COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          curl -u '${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }}' \
          ${{ vars.SERVER_ADDRESS }}/send \
          -F "chatroom=${{ vars.RELEASE_ROOM_ID }}" \
          -F $'message=# Neue Version für ${{ github.repository }}\nCommit-Nachricht:\n${{ env.COMMIT_MESSAGE }}'

  failure_notification:
    runs-on: ubuntu-latest
    needs: [build]
    if: failure()

    steps:
      - name: Notify failure
        env:
            JOB_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        run: |
          curl -u '${{ secrets.NEXTCLOUD_USERNAME }}:${{ secrets.NEXTCLOUD_PASSWORD }}' \
          ${{ vars.SERVER_ADDRESS }}/send \
          -F "chatroom=${{ vars.FAIL_ROOM_ID }}" \
          -F $'message=Job for __${{ github.repository }}__: ${{ github.event.head_commit.message }} failed.\nLink to the job: ${{ env.JOB_URL }}'
